//! Constitution compiler: concatenate hub rule files into a single CONSTITUTION.md.
//! Replaces scripts/compile_synapse_context.ps1.

use std::io::Write;
use std::path::{Path, PathBuf};

/// Default paths (relative to repo root) and titles, matching compile_synapse_context.ps1.
const INPUTS: &[(&str, &str)] = &[
    (
        "docs/setup/AGENTIC_OPERATOR_RULE.md",
        "AGENTIC OPERATOR RULE",
    ),
    ("docs/lessons_learned.md", "LESSONS LEARNED"),
    ("docs/RED_LINES.md", "RED LINES"),
    ("docs/setup/GSD_AND_MONOLITH.md", "GSD AND MONOLITH"),
];

const GENERATED_BY: &str = "Generated by rag-mcp compile-constitution. Do not edit this file by hand; edit the source docs under docs/ and re-run the command.";
const SOP_NOTE: &str = "For SOPs and skills, check SKILL_INDEX (docs/SKILL_INDEX.md) or query_knowledge(skill name). When the task requires a procedure or quality checklist, call list_skill_metadata then get_skill_content for the chosen skill.";

/// Concatenate hub rule files into one markdown document and write to output_path.
/// Repo root is used to resolve relative paths in INPUTS. Missing files are skipped.
pub fn run_compile_constitution(
    repo_root: &Path,
    output_path: &Path,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let mut out = Vec::<u8>::new();

    writeln!(out, "# Compiled Constitution (Hub Rules)")?;
    writeln!(out)?;
    writeln!(out, "{}", GENERATED_BY)?;
    writeln!(out)?;
    writeln!(out, "{}", SOP_NOTE)?;
    writeln!(out)?;
    writeln!(out, "---")?;
    writeln!(out)?;

    for (rel_path, title) in INPUTS {
        let full = repo_root.join(rel_path);
        if full.exists() {
            let content = std::fs::read_to_string(&full)?;
            writeln!(out, "## {}", title)?;
            writeln!(out)?;
            out.extend_from_slice(content.as_bytes());
            writeln!(out)?;
            writeln!(out, "---")?;
            writeln!(out)?;
        }
    }

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output_path, &out)?;
    eprintln!("Wrote {}", output_path.display());
    Ok(())
}

/// Resolve repo root: prefer explicit path, else parent of monolith (Cargo.toml), else cwd.
pub fn resolve_repo_root(explicit: Option<PathBuf>) -> PathBuf {
    if let Some(p) = explicit {
        return p.canonicalize().unwrap_or(p);
    }
    // When running from monolith/, parent is repo root.
    if let Ok(cwd) = std::env::current_dir() {
        let manifest = cwd.join("Cargo.toml");
        if manifest.exists() {
            // We're in monolith; repo root is parent.
            if cwd.file_name().map(|n| n == "monolith").unwrap_or(false) {
                return cwd.parent().map(PathBuf::from).unwrap_or(cwd);
            }
        }
        // Try parent for docs/
        let docs = cwd.join("docs");
        if docs.exists() {
            return cwd;
        }
        if let Some(parent) = cwd.parent() {
            let docs = parent.join("docs");
            if docs.exists() {
                return parent.to_path_buf();
            }
        }
        return cwd;
    }
    PathBuf::from(".")
}
